local Gui = require(script.Parent.DropLib):Init()
local cat = Gui:CreateCategory("Hello"):CreateSection("sex")
cat:CreateButton("lel",print)
local slider = cat:CreateSlider("asdf",print,0,1)
local slider = cat:CreateSlider("asdf",print,0,1)
local slider = cat:CreateSlider("asdf",print,0,1)
local slider = cat:CreateSlider("shesh",print,0,1,nil,true,0.33)
local box = cat:CreateTextBox("looll",print,nil,true,"YEET")
local cp = cat:CreateColorPicker("YO",print,false,Color3.new(1,0,0))
local switch = cat:CreateSwitch("asdf",print,true)
cat:CreateTextLabel("yaa yeet")
local selector = cat:CreateSelector("yeet",print,function()
    return workspace:GetDescendants()
end,"yeet")

local det = cat:CreateKeyDetector("asdf",print,Enum.KeyCode.A)
det:SetValue(Enum.KeyCode.B)